name: Build and deploy

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create SPA 404 fallback
        run: |
          # Ensure single-page app routes (like /admin) are served by index
          if [ -f build/index.html ]; then
            cp build/index.html build/404.html
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./build
          # Use a personal access token stored in GH secrets named GH_PAGES_PAT
          # Create a PAT with `repo` scope (and `workflow` if needed) and add it to
          # Settings > Secrets as GH_PAGES_PAT. This avoids 403 errors when GITHUB_TOKEN
          # lacks push rights (common for orgs or restricted repos).
          personal_token: ${{ secrets.GH_PAGES_PAT }}
